---
version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  mail:
    container_name: main
    image: tophfr/mailcatcher:latest
    ports:
      - "127.0.0.1:25:25"