---
version: "3.8"
services:
# Create docker-compose file, which could be used to run integration tests for this project

# looks like just add redis

# Service in container not only Redis
# How to build project and run it in container
# command line command bind to docker command
# Move port to properties
# Can be added logging outside of docker or just output couple of lines - automoted testing
# Check if compose file version is compatible with docker version
# exclude files by docker ignore
# port as a parameter